dist:     trusty
sudo:     required

language: c

os:
    - linux

compiler:
    - gcc

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       linux
          compiler: gcc

addons:
    apt:
        packages:
            - cmake
            - valgrind
            - cppcheck
            - lcov
            - gcovr

before_script:
    - sudo apt-get install -y libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt && sudo make
    - sudo cp *.a /usr/lib
    - cd "${TRAVIS_BUILD_DIR}"
    - cd HW_1
    - cmake .
    - make

script:
    - ./linters/run.sh --local
    - valgrind --track-origins=yes --leak-check=full ./TEST
    - cppcheck --enable=warning,performance,portability,style --language=c++ ./project
    - cd "${TRAVIS_BUILD_DIR}"
    - gcovr -r ..
    - bash <(curl -s https://codecov.io/bash)
