#env:
#    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
#    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

#matrix:
#    exclude:
#        - os:       linux
#          compiler: gcc

#install:
#    # скрипт настройки среды и установки зависимостей:
#    - source ci/travis/install-$TRAVIS_OS_NAME.sh

#script:
#    # скрипт сборки и тестирования проекта:
#    - mkdir build
#    - cd build
#    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
#    - cmake --build .
#    - ctest --output-on-failure


dist: trusty
sudo: required

language: c

os:
    - linux

compiler:
    - gcc

addons:
    apt:
        packages:
            - valgrind
            - cppcheck
            - clang
before_scripts:
    - sudo apt-get install -y libtest-dev
    - sudo pip install cpplint
script:
    - mkdir build
    - cd build
    - ctest --output-on-failure
    - cppcheck --std=c99 --enable=all -inconclusive src
    - cppcheck --std=c++11 --enable=all -inconclusive test
    - cpplint --filter=-legal/copyright,-readability/casting test/*.cpp
    - cpplint --filter=-legal/copyright,-readability/casting include/*.h
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
after_success:
    - valgrind  --show-leak-kinds=all --track-origins=yes --leak-check=full ./test.out